import argparse
import csv
from pathlib import Path
from typing import Dict, List, Sequence


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot class-balance histogram CSV files generated by example/train.py."
    )
    parser.add_argument(
        "--balance-csv",
        default="example/metrics/05-10_studentA_seed1_balance_hist_class_histogram.csv",
        help="Class histogram CSV from the class-balanced run.",
    )
    parser.add_argument(
        "--nobalance-csv",
        default="example/metrics/05-10_studentA_seed1_nobalance_hist_class_histogram.csv",
        help="Class histogram CSV from the no-class-balance run.",
    )
    parser.add_argument(
        "--output-dir",
        default="example/metrics",
        help="Directory used to save output plots.",
    )
    parser.add_argument(
        "--output-prefix",
        default="class_histogram",
        help="Prefix for output image filenames.",
    )
    parser.add_argument(
        "--max-batch",
        default=600,
        type=int,
        help="Only plot rows with global_batch_before <= this value.",
    )
    parser.add_argument(
        "--stage-batches",
        default=[0, 100, 200, 300, 400],
        nargs="+",
        type=int,
        help="Global batch values used in the key-stage bar plot.",
    )
    parser.add_argument(
        "--dpi",
        default=300,
        type=int,
        help="Output image resolution.",
    )
    return parser.parse_args()


def load_rows(csv_path: Path) -> List[Dict[str, str]]:
    with csv_path.open("r", newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"{csv_path} is empty")
    return rows


def count_columns(rows: Sequence[Dict[str, str]]) -> List[str]:
    return [name for name in rows[0].keys() if name.startswith("count_")]


def class_label(count_column: str) -> str:
    label = count_column.removeprefix("count_").replace("_", " ")
    return label.title()


def counts_for_row(row: Dict[str, str], columns: Sequence[str]) -> List[int]:
    return [int(row[column]) for column in columns]


def collapse_candidate_states(
    rows: Sequence[Dict[str, str]],
    columns: Sequence[str],
    max_batch: int,
) -> List[Dict[str, str]]:
    collapsed = []
    previous_key = None
    for row in sorted(rows, key=lambda item: int(item["global_batch_before"])):
        global_batch = int(row["global_batch_before"])
        if global_batch > max_batch:
            continue
        counts = tuple(counts_for_row(row, columns))
        key = (int(row["candidate_size"]), row["curriculum_finished"], counts)
        if key == previous_key:
            continue
        collapsed.append(row)
        previous_key = key
    return collapsed


def row_at_or_after_batch(
    rows: Sequence[Dict[str, str]],
    target_batch: int,
) -> Dict[str, str]:
    sorted_rows = sorted(rows, key=lambda item: int(item["global_batch_before"]))
    for row in sorted_rows:
        if int(row["global_batch_before"]) >= target_batch:
            return row
    return sorted_rows[-1]


def ensure_matplotlib():
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise RuntimeError("matplotlib is required for plotting class histograms.") from exc
    return plt


def plot_ratio_steps(
    plt,
    nobalance_rows: Sequence[Dict[str, str]],
    balance_rows: Sequence[Dict[str, str]],
    columns: Sequence[str],
    output_path: Path,
    dpi: int,
) -> None:
    labels = [class_label(column) for column in columns]
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5), sharey=True)
    for ax, rows, title in [
        (axes[0], nobalance_rows, "No Class Balance"),
        (axes[1], balance_rows, "Class Balance"),
    ]:
        x_values = [int(row["global_batch_before"]) for row in rows]
        for column, label in zip(columns, labels):
            y_values = [
                int(row[column]) / max(1, int(row["candidate_size"]))
                for row in rows
            ]
            ax.step(x_values, y_values, where="post", linewidth=2.0, label=label)
        ax.axhline(1 / len(columns), color="0.45", linestyle="--", linewidth=1.2)
        ax.set_title(title)
        ax.set_xlabel("Global Batch")
        ax.set_ylim(0, 0.55)
        ax.grid(alpha=0.25)
    axes[0].set_ylabel("Class Ratio in Candidate Pool")
    axes[1].legend(loc="center left", bbox_to_anchor=(1.02, 0.5), frameon=False)
    fig.suptitle("Candidate Pool Class Ratio During Curriculum")
    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def plot_stage_bars(
    plt,
    nobalance_rows: Sequence[Dict[str, str]],
    balance_rows: Sequence[Dict[str, str]],
    columns: Sequence[str],
    stage_batches: Sequence[int],
    output_path: Path,
    dpi: int,
) -> None:
    labels = [class_label(column) for column in columns]
    fig, axes = plt.subplots(
        len(stage_batches),
        2,
        figsize=(10, max(2.2 * len(stage_batches), 6)),
        sharey=False,
    )
    if len(stage_batches) == 1:
        axes = [axes]

    for row_idx, stage_batch in enumerate(stage_batches):
        nobalance_row = row_at_or_after_batch(nobalance_rows, stage_batch)
        balance_row = row_at_or_after_batch(balance_rows, stage_batch)
        row_counts = [
            counts_for_row(nobalance_row, columns),
            counts_for_row(balance_row, columns),
        ]
        row_ylim = max(max(counts) for counts in row_counts) * 1.15
        for col_idx, (row, title) in enumerate([
            (nobalance_row, "No Class Balance"),
            (balance_row, "Class Balance"),
        ]):
            ax = axes[row_idx][col_idx]
            counts = row_counts[col_idx]
            ax.bar(labels, counts, color=["#4C78A8", "#F58518", "#54A24B", "#E45756", "#72B7B2"])
            actual_batch = int(row["global_batch_before"])
            candidate_size = int(row["candidate_size"])
            ax.set_title(f"{title} | batch {actual_batch}, pool {candidate_size}")
            ax.set_ylim(0, row_ylim)
            ax.tick_params(axis="x", rotation=25)
            ax.grid(axis="y", alpha=0.25)
            if col_idx == 0:
                ax.set_ylabel("Sample Count")
    fig.suptitle("Class Counts in Key Curriculum Pools")
    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def plot_imbalance_gap(
    plt,
    nobalance_rows: Sequence[Dict[str, str]],
    balance_rows: Sequence[Dict[str, str]],
    columns: Sequence[str],
    output_path: Path,
    dpi: int,
) -> None:
    fig, ax = plt.subplots(figsize=(7.5, 4.5))
    for rows, label, color in [
        (nobalance_rows, "No Class Balance", "#D62728"),
        (balance_rows, "Class Balance", "#1F77B4"),
    ]:
        x_values = [int(row["global_batch_before"]) for row in rows]
        gaps = []
        for row in rows:
            counts = counts_for_row(row, columns)
            gaps.append(max(counts) - min(counts))
        ax.step(x_values, gaps, where="post", label=label, linewidth=2.2, color=color)
    ax.set_title("Candidate Pool Class Imbalance")
    ax.set_xlabel("Global Batch")
    ax.set_ylabel("Max Class Count - Min Class Count")
    ax.grid(alpha=0.25)
    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    args = parse_args()
    plt = ensure_matplotlib()

    balance_path = Path(args.balance_csv)
    nobalance_path = Path(args.nobalance_csv)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    balance_rows = load_rows(balance_path)
    nobalance_rows = load_rows(nobalance_path)
    columns = count_columns(balance_rows)
    if columns != count_columns(nobalance_rows):
        raise ValueError("Balance and no-balance CSV files have different count_* columns.")

    balance_states = collapse_candidate_states(balance_rows, columns, max_batch=args.max_batch)
    nobalance_states = collapse_candidate_states(nobalance_rows, columns, max_batch=args.max_batch)

    ratio_path = output_dir / f"{args.output_prefix}_ratio_steps.png"
    bars_path = output_dir / f"{args.output_prefix}_key_stage_bars.png"
    gap_path = output_dir / f"{args.output_prefix}_imbalance_gap.png"

    plot_ratio_steps(
        plt=plt,
        nobalance_rows=nobalance_states,
        balance_rows=balance_states,
        columns=columns,
        output_path=ratio_path,
        dpi=args.dpi,
    )
    plot_stage_bars(
        plt=plt,
        nobalance_rows=nobalance_states,
        balance_rows=balance_states,
        columns=columns,
        stage_batches=args.stage_batches,
        output_path=bars_path,
        dpi=args.dpi,
    )
    plot_imbalance_gap(
        plt=plt,
        nobalance_rows=nobalance_states,
        balance_rows=balance_states,
        columns=columns,
        output_path=gap_path,
        dpi=args.dpi,
    )

    print(f"Saved ratio plot: {ratio_path}")
    print(f"Saved key-stage bar plot: {bars_path}")
    print(f"Saved imbalance-gap plot: {gap_path}")


if __name__ == "__main__":
    main()
