import argparse
import csv
import math
from pathlib import Path
from typing import Dict, List, Tuple


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Plot multiple validation-curve CSV files generated by example/train.py into one figure."
        )
    )
    parser.add_argument(
        "csv_files",
        nargs="+",
        help="One or more CSV files (e.g. example/metrics/*_val_curve.csv).",
    )
    parser.add_argument(
        "--x",
        default="cumulative_batches",
        choices=["cumulative_batches", "epoch"],
        help="Column used as X axis.",
    )
    parser.add_argument(
        "--y",
        default="val_accuracy",
        help="Column used as Y axis.",
    )
    parser.add_argument(
        "--label-col",
        default="method",
        choices=["method", "run_name"],
        help="Column used for legend labels.",
    )
    parser.add_argument(
        "--title",
        default="Validation Curves Comparison",
        help="Figure title.",
    )
    parser.add_argument(
        "--aggregate",
        default="none",
        choices=["none", "mean", "mean_by_label"],
        help="Aggregation mode across input CSV files. "
             "'none' plots each file; 'mean' plots one mean curve across all files; "
             "'mean_by_label' groups by --label-col and plots one mean curve per group.",
    )
    parser.add_argument(
        "--std-shade",
        default=False,
        action="store_true",
        help="When using aggregated mode, draw mean +/- std shaded band.",
    )
    parser.add_argument(
        "--label",
        default="mean",
        help="Legend label used only when --aggregate mean is enabled.",
    )
    parser.add_argument(
        "--label-map",
        nargs="*",
        default=[],
        help="Optional exact label remapping entries in OLD=NEW format. "
             "Applied to legend labels; in --aggregate mean_by_label it is also used for grouping.",
    )
    parser.add_argument(
        "--every-n",
        default=1,
        type=int,
        help="Keep one point every N points for plotting (N>=1).",
    )
    parser.add_argument(
        "--smooth-window",
        default=1,
        type=int,
        help="Trailing moving-average window size on Y values (>=1).",
    )
    parser.add_argument(
        "--x-min",
        default=None,
        type=float,
        help="Optional lower bound for X-axis values. Only points with x >= x-min are plotted.",
    )
    parser.add_argument(
        "--x-max",
        default=None,
        type=float,
        help="Optional upper bound for X-axis values. Only points with x <= x-max are plotted.",
    )
    parser.add_argument(
        "--output",
        default="example/metrics/compare_val_curves.png",
        help="Output image path.",
    )
    return parser.parse_args()


def load_curve(csv_path: Path, x_col: str, y_col: str, label_col: str) -> Tuple[List[float], List[float], str]:
    with csv_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows: List[Dict[str, str]] = list(reader)

    if not rows:
        raise ValueError(f"{csv_path} is empty")

    required = [x_col, y_col, label_col]
    missing = [c for c in required if c not in rows[0]]
    if missing:
        raise ValueError(f"{csv_path} missing columns: {missing}")

    rows = sorted(rows, key=lambda r: float(r[x_col]))
    x = [float(r[x_col]) for r in rows]
    y = [float(r[y_col]) for r in rows]
    label = rows[0][label_col] or csv_path.stem

    return x, y, label


def _moving_average(values: List[float], window: int) -> List[float]:
    if window <= 1:
        return list(values)
    out: List[float] = []
    running_sum = 0.0
    for idx, value in enumerate(values):
        running_sum += value
        if idx >= window:
            running_sum -= values[idx - window]
            out.append(running_sum / window)
        else:
            out.append(running_sum / (idx + 1))
    return out


def _downsample(values: List[float], every_n: int) -> List[float]:
    if every_n <= 1:
        return list(values)
    return values[::every_n]


def _slice_by_x(
    x: List[float],
    y: List[float],
    x_min: float = None,
    x_max: float = None,
) -> Tuple[List[float], List[float]]:
    selected_x: List[float] = []
    selected_y: List[float] = []
    for xv, yv in zip(x, y):
        if x_min is not None and xv < x_min:
            continue
        if x_max is not None and xv > x_max:
            continue
        selected_x.append(xv)
        selected_y.append(yv)
    return selected_x, selected_y


def _slice_by_x_with_std(
    x: List[float],
    mean_y: List[float],
    std_y: List[float],
    x_min: float = None,
    x_max: float = None,
) -> Tuple[List[float], List[float], List[float]]:
    selected_x: List[float] = []
    selected_mean: List[float] = []
    selected_std: List[float] = []
    for xv, mv, sv in zip(x, mean_y, std_y):
        if x_min is not None and xv < x_min:
            continue
        if x_max is not None and xv > x_max:
            continue
        selected_x.append(xv)
        selected_mean.append(mv)
        selected_std.append(sv)
    return selected_x, selected_mean, selected_std


def _parse_label_map(entries: List[str]) -> Dict[str, str]:
    mapping: Dict[str, str] = {}
    for entry in entries:
        if "=" not in entry:
            raise ValueError(f"Invalid --label-map entry: '{entry}'. Expected OLD=NEW.")
        old, new = entry.split("=", 1)
        old = old.strip()
        new = new.strip()
        if not old:
            raise ValueError(f"Invalid --label-map entry: '{entry}'. OLD label cannot be empty.")
        mapping[old] = new
    return mapping


def plot_curves(
    csv_files: List[str],
    x_col: str,
    y_col: str,
    label_col: str,
    title: str,
    output: str,
    every_n: int,
    smooth_window: int,
    label_map: Dict[str, str],
    x_min: float,
    x_max: float,
):
    try:
        import matplotlib.pyplot as plt
    except ModuleNotFoundError as exc:
        raise RuntimeError("matplotlib is required to draw plots. Install it first, e.g. `pip install matplotlib`.") from exc

    plt.figure(figsize=(9, 5.5))

    for file_name in csv_files:
        csv_path = Path(file_name)
        x, y, label = load_curve(csv_path, x_col, y_col, label_col)
        label = label_map.get(label, label)
        y = _moving_average(y, smooth_window)
        x = _downsample(x, every_n)
        y = _downsample(y, every_n)
        x, y = _slice_by_x(x, y, x_min=x_min, x_max=x_max)
        if not x:
            continue
        plt.plot(x, y, marker="o", linewidth=1.5, markersize=3, label=label)

    plt.xlabel(x_col)
    plt.ylabel(y_col)
    plt.title(title)
    plt.grid(alpha=0.3)
    plt.legend()
    plt.tight_layout()

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=200)
    plt.close()

    print(f"Saved figure to: {output_path}")


def plot_mean_curve(
    csv_files: List[str],
    x_col: str,
    y_col: str,
    title: str,
    output: str,
    label: str,
    std_shade: bool,
    every_n: int,
    smooth_window: int,
    x_min: float,
    x_max: float,
):
    try:
        import matplotlib.pyplot as plt
    except ModuleNotFoundError as exc:
        raise RuntimeError("matplotlib is required to draw plots. Install it first, e.g. `pip install matplotlib`.") from exc

    curves: List[Tuple[List[float], List[float]]] = []
    for file_name in csv_files:
        csv_path = Path(file_name)
        x, y, _ = load_curve(csv_path, x_col, y_col, label_col="run_name")
        curves.append((x, y))

    if not curves:
        raise ValueError("No curves provided.")

    reference_x = curves[0][0]
    for idx, (x, _) in enumerate(curves[1:], start=2):
        if len(x) != len(reference_x):
            raise ValueError(
                f"CSV #{idx} has different length ({len(x)}) from first CSV ({len(reference_x)}). "
                "Please ensure all seeds have the same x-axis points."
            )
        for j, (a, b) in enumerate(zip(reference_x, x)):
            if not math.isclose(a, b, rel_tol=0.0, abs_tol=1e-9):
                raise ValueError(
                    f"CSV #{idx} x-axis mismatch at position {j}: {b} != {a}. "
                    "Please ensure all seeds share the same x-axis values."
                )

    point_count = len(reference_x)
    curve_count = len(curves)
    mean_y: List[float] = []
    std_y: List[float] = []
    for point_idx in range(point_count):
        values = [curves[curve_idx][1][point_idx] for curve_idx in range(curve_count)]
        avg = sum(values) / curve_count
        mean_y.append(avg)
        if curve_count > 1:
            var = sum((v - avg) ** 2 for v in values) / curve_count
            std_y.append(math.sqrt(var))
        else:
            std_y.append(0.0)

    mean_y = _moving_average(mean_y, smooth_window)
    std_y = _moving_average(std_y, smooth_window)
    plot_x = _downsample(reference_x, every_n)
    plot_mean_y = _downsample(mean_y, every_n)
    plot_std_y = _downsample(std_y, every_n)
    plot_x, plot_mean_y, plot_std_y = _slice_by_x_with_std(
        plot_x,
        plot_mean_y,
        plot_std_y,
        x_min=x_min,
        x_max=x_max,
    )
    if not plot_x:
        raise ValueError("No points left after applying x-axis range filters.")

    plt.figure(figsize=(9, 5.5))
    plt.plot(plot_x, plot_mean_y, marker="o", linewidth=2.0, markersize=3, label=label)
    if std_shade:
        lower = [m - s for m, s in zip(plot_mean_y, plot_std_y)]
        upper = [m + s for m, s in zip(plot_mean_y, plot_std_y)]
        plt.fill_between(plot_x, lower, upper, alpha=0.2, label=f"{label} +/- std")

    plt.xlabel(x_col)
    plt.ylabel(y_col)
    plt.title(title)
    plt.grid(alpha=0.3)
    plt.legend()
    plt.tight_layout()

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=200)
    plt.close()
    print(f"Saved figure to: {output_path}")


def _validate_x_alignment(curves: List[Tuple[List[float], List[float]]], group_name: str):
    if not curves:
        raise ValueError(f"No curves found for group '{group_name}'.")
    reference_x = curves[0][0]
    for idx, (x, _) in enumerate(curves[1:], start=2):
        if len(x) != len(reference_x):
            raise ValueError(
                f"Group '{group_name}' CSV #{idx} has different length ({len(x)}) from first CSV ({len(reference_x)}). "
                "Please ensure all seeds in the same mode have the same x-axis points."
            )
        for j, (a, b) in enumerate(zip(reference_x, x)):
            if not math.isclose(a, b, rel_tol=0.0, abs_tol=1e-9):
                raise ValueError(
                    f"Group '{group_name}' CSV #{idx} x-axis mismatch at position {j}: {b} != {a}. "
                    "Please ensure all seeds in the same mode share the same x-axis values."
                )


def _compute_mean_std(curves: List[Tuple[List[float], List[float]]]) -> Tuple[List[float], List[float], List[float]]:
    reference_x = curves[0][0]
    point_count = len(reference_x)
    curve_count = len(curves)
    mean_y: List[float] = []
    std_y: List[float] = []
    for point_idx in range(point_count):
        values = [curves[curve_idx][1][point_idx] for curve_idx in range(curve_count)]
        avg = sum(values) / curve_count
        mean_y.append(avg)
        if curve_count > 1:
            var = sum((v - avg) ** 2 for v in values) / curve_count
            std_y.append(math.sqrt(var))
        else:
            std_y.append(0.0)
    return reference_x, mean_y, std_y


def plot_mean_curves_by_label(
    csv_files: List[str],
    x_col: str,
    y_col: str,
    label_col: str,
    title: str,
    output: str,
    std_shade: bool,
    every_n: int,
    smooth_window: int,
    label_map: Dict[str, str],
    x_min: float,
    x_max: float,
):
    try:
        import matplotlib.pyplot as plt
    except ModuleNotFoundError as exc:
        raise RuntimeError("matplotlib is required to draw plots. Install it first, e.g. `pip install matplotlib`.") from exc

    grouped_curves: Dict[str, List[Tuple[List[float], List[float]]]] = {}
    for file_name in csv_files:
        csv_path = Path(file_name)
        x, y, label = load_curve(csv_path, x_col, y_col, label_col=label_col)
        label = label_map.get(label, label)
        grouped_curves.setdefault(label, []).append((x, y))

    if not grouped_curves:
        raise ValueError("No curves provided.")

    plt.figure(figsize=(9, 5.5))
    for group_label in sorted(grouped_curves.keys()):
        curves = grouped_curves[group_label]
        _validate_x_alignment(curves, group_name=group_label)
        reference_x, mean_y, std_y = _compute_mean_std(curves)

        mean_y = _moving_average(mean_y, smooth_window)
        std_y = _moving_average(std_y, smooth_window)
        plot_x = _downsample(reference_x, every_n)
        plot_mean_y = _downsample(mean_y, every_n)
        plot_std_y = _downsample(std_y, every_n)
        plot_x, plot_mean_y, plot_std_y = _slice_by_x_with_std(
            plot_x,
            plot_mean_y,
            plot_std_y,
            x_min=x_min,
            x_max=x_max,
        )
        if not plot_x:
            continue

        line = plt.plot(plot_x, plot_mean_y, marker="o", linewidth=2.0, markersize=3, label=group_label)[0]
        if std_shade:
            lower = [m - s for m, s in zip(plot_mean_y, plot_std_y)]
            upper = [m + s for m, s in zip(plot_mean_y, plot_std_y)]
            plt.fill_between(plot_x, lower, upper, alpha=0.15, color=line.get_color())

    plt.xlabel(x_col)
    plt.ylabel(y_col)
    plt.title(title)
    plt.grid(alpha=0.3)
    plt.legend()
    plt.tight_layout()

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=200)
    plt.close()
    print(f"Saved figure to: {output_path}")


if __name__ == "__main__":
    args = parse_args()
    if args.every_n < 1:
        raise ValueError("--every-n must be >= 1.")
    if args.smooth_window < 1:
        raise ValueError("--smooth-window must be >= 1.")
    if args.x_min is not None and args.x_max is not None and args.x_min > args.x_max:
        raise ValueError("--x-min must be <= --x-max.")
    label_map = _parse_label_map(args.label_map)

    if args.aggregate == "mean":
        plot_mean_curve(
            csv_files=args.csv_files,
            x_col=args.x,
            y_col=args.y,
            title=args.title,
            output=args.output,
            label=args.label,
            std_shade=args.std_shade,
            every_n=args.every_n,
            smooth_window=args.smooth_window,
            x_min=args.x_min,
            x_max=args.x_max,
        )
    elif args.aggregate == "mean_by_label":
        plot_mean_curves_by_label(
            csv_files=args.csv_files,
            x_col=args.x,
            y_col=args.y,
            label_col=args.label_col,
            title=args.title,
            output=args.output,
            std_shade=args.std_shade,
            every_n=args.every_n,
            smooth_window=args.smooth_window,
            label_map=label_map,
            x_min=args.x_min,
            x_max=args.x_max,
        )
    else:
        plot_curves(
            csv_files=args.csv_files,
            x_col=args.x,
            y_col=args.y,
            label_col=args.label_col,
            title=args.title,
            output=args.output,
            every_n=args.every_n,
            smooth_window=args.smooth_window,
            label_map=label_map,
            x_min=args.x_min,
            x_max=args.x_max,
        )
