import argparse
import csv
import math
from pathlib import Path
from typing import Dict, List, Tuple


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Plot multiple validation-curve CSV files generated by example/train.py into one figure."
        )
    )
    parser.add_argument(
        "csv_files",
        nargs="+",
        help="One or more CSV files (e.g. example/metrics/*_val_curve.csv).",
    )
    parser.add_argument(
        "--x",
        default="cumulative_batches",
        choices=["cumulative_batches", "epoch"],
        help="Column used as X axis.",
    )
    parser.add_argument(
        "--y",
        default="val_accuracy",
        help="Column used as Y axis.",
    )
    parser.add_argument(
        "--label-col",
        default="method",
        choices=["method", "run_name"],
        help="Column used for legend labels.",
    )
    parser.add_argument(
        "--title",
        default="Validation Curves Comparison",
        help="Figure title.",
    )
    parser.add_argument(
        "--aggregate",
        default="none",
        choices=["none", "mean"],
        help="Aggregation mode across input CSV files. 'none' plots each file; 'mean' plots mean curve aligned by X.",
    )
    parser.add_argument(
        "--std-shade",
        default=False,
        action="store_true",
        help="When --aggregate mean is used, draw mean +/- std shaded band.",
    )
    parser.add_argument(
        "--label",
        default="mean",
        help="Legend label used when --aggregate mean is enabled.",
    )
    parser.add_argument(
        "--output",
        default="example/metrics/compare_val_curves.png",
        help="Output image path.",
    )
    return parser.parse_args()


def load_curve(csv_path: Path, x_col: str, y_col: str, label_col: str) -> Tuple[List[float], List[float], str]:
    with csv_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows: List[Dict[str, str]] = list(reader)

    if not rows:
        raise ValueError(f"{csv_path} is empty")

    required = [x_col, y_col, label_col]
    missing = [c for c in required if c not in rows[0]]
    if missing:
        raise ValueError(f"{csv_path} missing columns: {missing}")

    rows = sorted(rows, key=lambda r: float(r[x_col]))
    x = [float(r[x_col]) for r in rows]
    y = [float(r[y_col]) for r in rows]
    label = rows[0][label_col] or csv_path.stem

    return x, y, label


def plot_curves(csv_files: List[str], x_col: str, y_col: str, label_col: str, title: str, output: str):
    try:
        import matplotlib.pyplot as plt
    except ModuleNotFoundError as exc:
        raise RuntimeError("matplotlib is required to draw plots. Install it first, e.g. `pip install matplotlib`.") from exc

    plt.figure(figsize=(9, 5.5))

    for file_name in csv_files:
        csv_path = Path(file_name)
        x, y, label = load_curve(csv_path, x_col, y_col, label_col)
        plt.plot(x, y, marker="o", linewidth=1.5, markersize=3, label=label)

    plt.xlabel(x_col)
    plt.ylabel(y_col)
    plt.title(title)
    plt.grid(alpha=0.3)
    plt.legend()
    plt.tight_layout()

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=200)
    plt.close()

    print(f"Saved figure to: {output_path}")


def plot_mean_curve(
    csv_files: List[str],
    x_col: str,
    y_col: str,
    title: str,
    output: str,
    label: str,
    std_shade: bool,
):
    try:
        import matplotlib.pyplot as plt
    except ModuleNotFoundError as exc:
        raise RuntimeError("matplotlib is required to draw plots. Install it first, e.g. `pip install matplotlib`.") from exc

    curves: List[Tuple[List[float], List[float]]] = []
    for file_name in csv_files:
        csv_path = Path(file_name)
        x, y, _ = load_curve(csv_path, x_col, y_col, label_col="run_name")
        curves.append((x, y))

    if not curves:
        raise ValueError("No curves provided.")

    reference_x = curves[0][0]
    for idx, (x, _) in enumerate(curves[1:], start=2):
        if len(x) != len(reference_x):
            raise ValueError(
                f"CSV #{idx} has different length ({len(x)}) from first CSV ({len(reference_x)}). "
                "Please ensure all seeds have the same x-axis points."
            )
        for j, (a, b) in enumerate(zip(reference_x, x)):
            if not math.isclose(a, b, rel_tol=0.0, abs_tol=1e-9):
                raise ValueError(
                    f"CSV #{idx} x-axis mismatch at position {j}: {b} != {a}. "
                    "Please ensure all seeds share the same x-axis values."
                )

    point_count = len(reference_x)
    curve_count = len(curves)
    mean_y: List[float] = []
    std_y: List[float] = []
    for point_idx in range(point_count):
        values = [curves[curve_idx][1][point_idx] for curve_idx in range(curve_count)]
        avg = sum(values) / curve_count
        mean_y.append(avg)
        if curve_count > 1:
            var = sum((v - avg) ** 2 for v in values) / curve_count
            std_y.append(math.sqrt(var))
        else:
            std_y.append(0.0)

    plt.figure(figsize=(9, 5.5))
    plt.plot(reference_x, mean_y, marker="o", linewidth=2.0, markersize=3, label=label)
    if std_shade:
        lower = [m - s for m, s in zip(mean_y, std_y)]
        upper = [m + s for m, s in zip(mean_y, std_y)]
        plt.fill_between(reference_x, lower, upper, alpha=0.2, label=f"{label} +/- std")

    plt.xlabel(x_col)
    plt.ylabel(y_col)
    plt.title(title)
    plt.grid(alpha=0.3)
    plt.legend()
    plt.tight_layout()

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=200)
    plt.close()
    print(f"Saved figure to: {output_path}")


if __name__ == "__main__":
    args = parse_args()
    if args.aggregate == "mean":
        plot_mean_curve(
            csv_files=args.csv_files,
            x_col=args.x,
            y_col=args.y,
            title=args.title,
            output=args.output,
            label=args.label,
            std_shade=args.std_shade,
        )
    else:
        plot_curves(
            csv_files=args.csv_files,
            x_col=args.x,
            y_col=args.y,
            label_col=args.label_col,
            title=args.title,
            output=args.output,
        )
