import argparse
import csv
from pathlib import Path
from typing import Dict, List, Tuple


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Plot multiple validation-curve CSV files generated by example/train.py into one figure."
        )
    )
    parser.add_argument(
        "csv_files",
        nargs="+",
        help="One or more CSV files (e.g. example/metrics/*_val_curve.csv).",
    )
    parser.add_argument(
        "--x",
        default="cumulative_batches",
        choices=["cumulative_batches", "epoch"],
        help="Column used as X axis.",
    )
    parser.add_argument(
        "--y",
        default="val_accuracy",
        help="Column used as Y axis.",
    )
    parser.add_argument(
        "--label-col",
        default="method",
        choices=["method", "run_name"],
        help="Column used for legend labels.",
    )
    parser.add_argument(
        "--title",
        default="Validation Curves Comparison",
        help="Figure title.",
    )
    parser.add_argument(
        "--output",
        default="example/metrics/compare_val_curves.png",
        help="Output image path.",
    )
    return parser.parse_args()


def load_curve(csv_path: Path, x_col: str, y_col: str, label_col: str) -> Tuple[List[float], List[float], str]:
    with csv_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows: List[Dict[str, str]] = list(reader)

    if not rows:
        raise ValueError(f"{csv_path} is empty")

    required = [x_col, y_col, label_col]
    missing = [c for c in required if c not in rows[0]]
    if missing:
        raise ValueError(f"{csv_path} missing columns: {missing}")

    rows = sorted(rows, key=lambda r: float(r[x_col]))
    x = [float(r[x_col]) for r in rows]
    y = [float(r[y_col]) for r in rows]
    label = rows[0][label_col] or csv_path.stem

    return x, y, label


def plot_curves(csv_files: List[str], x_col: str, y_col: str, label_col: str, title: str, output: str):
    try:
        import matplotlib.pyplot as plt
    except ModuleNotFoundError as exc:
        raise RuntimeError("matplotlib is required to draw plots. Install it first, e.g. `pip install matplotlib`.") from exc

    plt.figure(figsize=(9, 5.5))

    for file_name in csv_files:
        csv_path = Path(file_name)
        x, y, label = load_curve(csv_path, x_col, y_col, label_col)
        plt.plot(x, y, marker="o", linewidth=1.5, markersize=3, label=label)

    plt.xlabel(x_col)
    plt.ylabel(y_col)
    plt.title(title)
    plt.grid(alpha=0.3)
    plt.legend()
    plt.tight_layout()

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=200)
    plt.close()

    print(f"Saved figure to: {output_path}")


if __name__ == "__main__":
    args = parse_args()
    plot_curves(
        csv_files=args.csv_files,
        x_col=args.x,
        y_col=args.y,
        label_col=args.label_col,
        title=args.title,
        output=args.output,
    )
